version: "3"

services:
  server:
    build:
      context: .
      target: develop
    command: ["npm", "run", "dev"]
    volumes:
      - .:/develop
      - /develop/node_modules
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
