version: "3"

services:
  server:
    build: .
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      APP_SECRET: appSecret
      DATABASE_URL: postgresql://postgres:password@db:5432

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
