apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: graphql
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: graphql
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: graphql
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: graphql-init-migrate
          image: ghcr.io/pokernook/graphql:0.0.2 # {"$imagepolicy": "flux-system:graphql"}
          command:
            - npm
            - run
            - prisma:migrate:deploy
            - --
            - --schema=dist/schema.prisma
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: postgres-url
      containers:
        - name: graphql
          image: ghcr.io/pokernook/graphql:0.0.2 # {"$imagepolicy": "flux-system:graphql"}
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: app-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: postgres-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-secrets
                  key: redis-url
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: node-env
            - name: PORT
              value: "4000"
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
          ports:
            - name: http
              containerPort: 4000
