apiVersion: batch/v1
kind: Job
metadata:
  name: graph-migrate
  namespace: flux-system
spec:
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: graph-migrate
          image: ghcr.io/pokernook/graph:0.0.1 # {"$imagepolicy": "flux-system:graph"}
          command:
            - npm
            - run
            - prisma:migrate:deploy
            - --
            - --schema=dist/schema.prisma
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graph-secrets
                  key: postgres-url
