name: Check Container Build

on:
  push: # TODO: Remove this event before merge
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install DevSpace
        run: npm install -g devspace

      - run: devspace build --profile production --skip-push
