name: Check Container Build

on:
  push: # TODO: Remove this event before merge
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker run devspacesh/devspace devspace build --profile production --skip-push
      # - uses: docker/setup-buildx-action@v1

      # - uses: docker/build-push-action@v2
      # with:
      # push: false
