name: Container Testing

on:
  push:

jobs:
  yeet:
    name: Yeet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: ghcr.io/pokernook/graph:0.0.1
