name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  migrate-database:
    name: Migrate Database
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Migrations
        run: |
          npm ci
          yes 2>/dev/null | npm run prisma:migrate:up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  publish-container:
    name: Publish Container
    runs-on: ubuntu-latest
    needs: migrate-database
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean CR
        run: doctl registry login --expiry-seconds 600

      - name: Prepare Container
        id: prepare
        run: |
          URI=registry.digitalocean.com/pokernook/graph
          TAG="${URI}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tag::${TAG}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
