name: Generate GraphQL Schema

on:
  push:

jobs:
  generate-schema:
    name: Generate Schema
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Reflect App
        run: |
          npm ci
          npm run nexus:reflect

      - name: Commit Schema
        uses: EndBug/add-and-commit@v5
        with:
          add: "*.graphql"
          message: "Generate schema"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
