name: Lint

on:
  push:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Run ESLint Script
        run: |
          npm ci
          npm run generate
          npm run lint

      - name: Commit ESLint Fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix ESLint problems
