name: Publish Container

on:
  push:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Container
        id: prepare
        run: |
          IMAGE=${{ env.cr_server }}/pokernook/graph
          TAG="${IMAGE}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: 445789524075.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-task
        with:
          task-definition: .aws/ecs-task-definition.json
          container-name: graph
          image: ${{ steps.prepare.outputs.tag }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          cluster: pokernook
          service: graph
          wait-for-service-stability: true
