name: Publish Container

on:
  push:

env:
  cr_server: 445789524075.dkr.ecr.us-east-1.amazonaws.com
  cr_username: ${{ secrets.AWS_ACCESS_KEY_ID }}
  cr_password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Container
        id: prepare
        run: |
          IMAGE=${{ env.cr_server }}/pokernook/graph
          TAG="${IMAGE}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.cr_server }}
          username: ${{ env.cr_username }}
          password: ${{ env.cr_password }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
