name: Serverless Deploy

on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: production

jobs:
  rollout-function:
    name: Rollout Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build App
        run: npm ci && npm run build

      - name: Deploy Function
        run: |
          npx serverless deploy --stage prod
          npm run migrate:up
