name: Serverless Preview

on:
  push: # TODO: Serverless deployments shouldn't happen on push
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# TODO: Add deployment cleanup job, conditional on PR status
# TODO: Determine deploy stage based on PR branch
# TODO: Run DB migrations & seeding after deployment

jobs:
  manage-function:
    name: Manage Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout PR Head
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout HEAD^2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build App
        run: npm ci && npm run build

      - name: Deploy Preview
        run: npx serverless deploy --stage preview
